/**
 * Brand-level configuration. Everything that could change about the brand lives here.
 * Pages and components import from this file — never hard-code these values elsewhere.
 */

// TODO(pre-launch): confirm final brand name.
export const BRAND_NAME = 'AutoToolKitPH';

export const TAGLINE = 'Practical automotive tools, guides & systems for Filipinos';

// Facebook Page username. Every m.me link (buy buttons, privacy contact) is built from this.
export const FB_PAGE_NAME: string = 'AutoToolKitPH';

// Used via the {YEARS_EXPERIENCE} token.
export const YEARS_EXPERIENCE: string = '10';

// Used via the {DELIVERY_HOURS} token.
export const DELIVERY_HOURS = '8AM–12MN';

/**
 * Meta Pixel ID, read from the PUBLIC_META_PIXEL_ID environment variable at build time.
 * Set it in Vercel → Project → Settings → Environment Variables (Production), then redeploy.
 * For local testing, put PUBLIC_META_PIXEL_ID=... in a .env file (not committed).
 * While empty, Meta's Pixel script is NOT loaded and no events are sent.
 */
export const META_PIXEL_ID: string = readEnv('PUBLIC_META_PIXEL_ID');

/**
 * TODO(pre-launch): your production URL with no trailing slash, e.g. "https://autotoolkitph.com".
 * Used for canonical URLs, Open Graph URLs, JSON-LD and the sitemap.
 * While empty, builds on Vercel fall back to the project's production domain
 * (VERCEL_PROJECT_PRODUCTION_URL); local builds fall back to http://localhost:4321.
 */
export const SITE_URL: string = '';

export const PAYMENT_METHODS = ['GCash'];

/** Account name as GCash itself masks it. Never put the full name on the site. */
export const GCASH_NAME_MASKED = 'RO****O J* D.';

/**
 * GCash number for the "Send money" option on /bayad, read from PUBLIC_GCASH_NUMBER at build time
 * (Vercel → Settings → Environments → Production). While empty, /bayad shows the QR only.
 */
export const GCASH_NUMBER: string = readEnv('PUBLIC_GCASH_NUMBER');

/** Starter Kit buyers can get the Auto Service Center System for this amount. */
export const UPGRADE_PRICE = 1500;

export const GUARANTEE_TEXT = '7-day money-back guarantee';

/** Show products with status "coming-soon" on the homepage as non-clickable cards. */
export const SHOW_COMING_SOON: boolean = false;

export const FB_PAGE_URL = `https://www.facebook.com/${FB_PAGE_NAME}`;
export const MESSENGER_BASE = `https://m.me/${FB_PAGE_NAME}`;

export const LOGOS = {
  /** Header, on light backgrounds. All logo SVGs are generated by scripts/make-logos.mjs. */
  horizontalLight: { src: '/brand/logo-horizontal-light.svg', width: 212, height: 32 },
  /** Product mockup cover and other dark surfaces */
  horizontalDark: { src: '/brand/logo-horizontal-dark.svg', width: 212, height: 32 },
  /** Footer (dark) */
  stackedDark: { src: '/brand/logo-stacked-dark.svg', width: 140, height: 125 },
  /** Favicon and schema.org logo */
  mark: { src: '/brand/logo-mark.svg', width: 64, height: 64 },
};

export const OG_DEFAULT = '/brand/og-default.jpg';

/**
 * Read a build-time environment variable. Works both inside Astro (import.meta.env, which
 * includes .env files) and in astro.config.ts / plain Node (process.env, which is where
 * Vercel puts dashboard variables).
 */
export function readEnv(name: string): string {
  const fromVite = (import.meta as { env?: Record<string, string | undefined> }).env?.[name];
  const fromNode = (globalThis as { process?: { env?: Record<string, string | undefined> } }).process?.env?.[name];
  return (fromVite ?? fromNode ?? '').trim();
}

/** Git commit and Vercel environment of this build, stamped into every page as <meta name="x-build">. */
export const BUILD_COMMIT = readEnv('VERCEL_GIT_COMMIT_SHA').slice(0, 7) || 'local';
export const BUILD_ENV = readEnv('VERCEL_ENV') || 'local';

export function resolveSiteUrl(): string {
  if (SITE_URL) return SITE_URL.replace(/\/+$/, '');
  // Vercel sets this at build time.
  const vercel = readEnv('VERCEL_PROJECT_PRODUCTION_URL');
  if (vercel) return `https://${vercel}`;
  return 'http://localhost:4321';
}
